<?php

/**
 * Concatenates receiver/src/*.php (the testable, autoloadable class files)
 * into one dependency-free file at receiver/dist/deploy-receiver.php.
 * That dist file is the ONLY thing that needs to be uploaded to cPanel.
 */

$srcDir = __DIR__ . '/src';
$distDir = __DIR__ . '/dist';
if (!is_dir($distDir)) {
    mkdir($distDir, 0755, true);
}

$classFiles = [
    'Auth.php',
    'ChunkUploader.php',
    'Extractor.php',
    'BackupManager.php',
    'Applier.php',
    'DeployLog.php',
    'Rollback.php',
    'Router.php',
];

$collectedUses = [];

function stripPhpWrapper(string $code, array &$collectedUses): string
{
    $code = preg_replace('/^<\?php\s*/', '', $code);
    $code = preg_replace('/^namespace\s+[^;]+;\s*/m', '', $code);
    $code = preg_replace_callback('/^use\s+([^;]+);\s*\n/m', function ($m) use (&$collectedUses) {
        $collectedUses[trim($m[1])] = true;
        return '';
    }, $code);
    return trim($code) . "\n";
}

$classesCode = '';
foreach ($classFiles as $file) {
    $classesCode .= stripPhpWrapper(file_get_contents($srcDir . '/' . $file), $collectedUses) . "\n";
}

$useStatements = '';
foreach (array_keys($collectedUses) as $use) {
    $useStatements .= "use {$use};\n";
}

$uiHtml = file_get_contents($srcDir . '/views/ui.php');
$uiHtmlEscaped = str_replace(['\\', "'"], ['\\\\', "\\'"], $uiHtml);

$header = <<<'PHP'
<?php

/**
 * Deployer receiver - single-file build. DO NOT EDIT DIRECTLY except the
 * CONFIGURATION block below; this file is generated by receiver/build.php
 * from receiver/src/*.php.
 *
 * ============================ CONFIGURATION ============================
 * Fill these in after uploading, then remove/rename this comment reminder.
 */

namespace Deployer\Receiver;

// sha256 of a long random API token, for header-based auth (X-Deploy-Token).
// Generate a token:      php -r "echo bin2hex(random_bytes(32));"
// Hash it:               php -r "echo hash('sha256', 'YOUR_TOKEN_HERE');"
const TOKEN_HASH = 'CHANGE_ME';

// password_hash() of the web UI login password.
// Generate with:         php -r "echo password_hash('YOUR_PASSWORD', PASSWORD_DEFAULT);"
const PASSWORD_HASH = 'CHANGE_ME';

// Deployment target directory. Defaults to this file's directory.
const WEB_ROOT = __DIR__;

// Work/backup/log locations. Recommended: outside the public web root, or
// protected by a .htaccess "Deny from all" if they must live inside it.
const WORK_DIR = __DIR__ . '/.deployer-work';
const BACKUP_DIR = __DIR__ . '/.deployer-backups';
const LOG_PATH = __DIR__ . '/.deployer-log.json';

/* ========================================================================= */

PHP;

$footer = <<<'PHP'

$config = [
    'token_hash' => TOKEN_HASH,
    'password_hash' => PASSWORD_HASH,
    'web_root' => WEB_ROOT,
    'work_dir' => WORK_DIR,
    'backup_dir' => BACKUP_DIR,
    'log_path' => LOG_PATH,
];

$auth = new Auth($config['token_hash'], $config['password_hash']);
$uploader = new ChunkUploader($config['work_dir']);
$extractor = new Extractor();
$backupManager = new BackupManager($config['backup_dir'], $config['web_root']);
$applier = new Applier($config['web_root']);
$log = new DeployLog($config['log_path']);
$rollback = new Rollback($config['backup_dir'], $config['web_root']);
$router = new Router($auth, $uploader, $extractor, $backupManager, $applier, $log, $rollback, $config['work_dir']);

session_start();

$action = $_GET['action'] ?? $_POST['action'] ?? null;

if ($action === null) {
    echo UI_HTML;
    exit;
}

$input = array_merge($_GET, $_POST);
$tokenHeader = $_SERVER['HTTP_X_DEPLOY_TOKEN'] ?? null;
$rawBodyReader = function () {
    return file_get_contents('php://input');
};

$result = $router->dispatch($action, $input, $_SESSION, $tokenHeader, $rawBodyReader);

http_response_code($result['status']);
header('Content-Type: application/json');
echo json_encode($result['body']);
PHP;

$uiConstant = "const UI_HTML = '" . $uiHtmlEscaped . "';\n\n";

$output = $header . "\n" . $useStatements . "\n" . $uiConstant . $classesCode . $footer . "\n";

file_put_contents($distDir . '/deploy-receiver.php', $output);

echo "Built " . $distDir . "/deploy-receiver.php (" . strlen($output) . " bytes)\n";
